sudo: required
dist: trusty
addons:
  firefox: 'latest'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - node_modules/
language: node_js

node_js:
  - "node"

before_script:
  - npm install -g bower
  - npm install -g polymer-cli
  - bower i

script: xvfb-run npm run test-build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/es5-bundled
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
